- sudo apt update && sudo apt install build-essential
- Install go 1.18 latest
- export GOPATH=$HOME/go
- export GOBIN=${GOPATH}/bin
- export PATH=$PATH:$GOBIN:/usr/local/go/bin
- Clone the bluzelle-public repo: https://github.com/bluzelle/bluzelle-public
- Checkout devel
- Install ignite (you may have to install it as root, with sudo): curl https://get.ignite.com/cli! | bash
- Run "ignite chain serve -f -v" in the "bluzelle-public/curium" folder (of the cloned repo) to scaffold and start a local validator environment with curiumd built, paths set, etc. This also sets up ~/.curiumd for all the data for this node. This will actually start a new chain.
- Stop the chain with CTRL-C.
- Run "curiumd unsafe-reset-all". We want the environment but a clean one.
- Replace ~/.curium/config/genesis.json with the one from https://a.client.sentry.neerajnet.bluzelle.com:26657/genesis
- Modify ~/.curium/config/config.toml and set the peers in the “persistent_peers” section. Peer with 3da38ed63bcecd4084f9cd83ecd39e5c30cb0972@a.gateway.sentry.neerajnet.bluzelle.com:26656
- Run "curiumd start" to start your node.