# my global config
global:
  scrape_interval:     30s
  evaluation_interval: 30s

rule_files:
  - rules/alerts/exporter*
  - rules/alerts/bluzelle*
  - rules/alerts/node.rules
  - rules/alerts/node.disk.rules

scrape_configs:
   - job_name: mainnet
     file_sd_configs:
       - refresh_interval: 1m
         files:
           - 'sd/mainnet/*.yml'
   - job_name: testnet 
     file_sd_configs:
       - refresh_interval: 1m
         files:
           - 'sd/testnet/*.yml'
